name:                metro-transport-tls
version:             0.1.0.0
github:              "Lupino/metro"
license:             BSD3
author:              "Lupino"
maintainer:          "lmjubuntu@gmail.com"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            TLS transport for metro
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Lupino/metro/tree/master/metro-transport-tls#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - bytestring
  - metro
  - tls
  - crypton-x509-validation
  - crypton-x509
  - crypton-x509-store
  - data-default-class
  - pem
