name:                metro-transport-crypto
version:             0.1.0.0
github:              "Lupino/metro"
license:             BSD3
author:              "Lupino"
maintainer:          "lmjubuntu@gmail.com"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Crypto transport for metro
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Lupino/metro/tree/master/metro-transport-crypto#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - bytestring
  - binary
  - metro
  - unliftio
  - cryptonite
  - text

tests:
  metro-transport-crypto-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - metro-transport-crypto
    - metro
    - QuickCheck
    - quickcheck-instances
    - cryptonite
    - bytestring
